### PR TITLE
Feature/context

### PR DESCRIPTION
**Pull request by nicholas-myers**
## Before making the Pull Request:

Created the relationship for questions and contexts as well as set up some seed data for contexts, with the endpoint to get a list of questions associated with a context as well as an endpoint for all contexts.

- [x] Is there a description to this pull request that points to a specific user story, feature, or bugfix?
- [x] Are there comments where the code may be unclear?
- [x] Is all dead code, commented out code, etc. removed?
- [ ] Are there tests written for these changes?
- [ ] Does the ReadMe need to be updated?

## Before being merged by the TPL:

- [ ] Has the pull request been reviewed by at least two team members? 
- [ ] Did they leave any comments or suggestions? 
- [ ] Were those suggestions acted on?
- [ ] Are all tests passing?
- [ ] Has the documentation been updated?

### CODE REVIEW

**Review by mcelroyian — CHANGES_REQUESTED** [review]
You are modifying 229 files. Too big of a change. get rid of the .idea and target stuff.

**Review by Caleb-Barger — APPROVED** [review]
did you git add . ??

**Review by Caleb-Barger — CHANGES_REQUESTED** [review]
Check your git status something is weird

**Comment by nicholas-myers** [comment]
I made a mistake, will delete the branch and start new PR

**Pull request closed without merging**
