### PR TITLE
Feature/member can respond to survey

### PR DESCRIPTION
**Pull request by Caleb-Barger**
## Before making the Pull Request:

members can now respond to questions.

- [x] Is there a description to this pull request that points to a specific user story, feature, or bugfix?
- [x] Are there comments where the code may be unclear?
- [x] Is all dead code, commented out code, etc. removed?
- [ ] Are there tests written for these changes?
- [x] Does the ReadMe need to be updated?

## Before being merged by the TPL:

- [ ] Has the pull request been reviewed by at least two team members? 
- [ ] Did they leave any comments or suggestions? 
- [ ] Were those suggestions acted on?
- [ ] Are all tests passing?
- [ ] Has the documentation been updated?

### CODE REVIEW

**Review by mcelroyian — COMMENTED** [review]
Do we need to create a new model, AnswerMinimum?

Is there a benefit above just using the existing Answer model?

**Comment by Caleb-Barger** [comment]
i was thinking the new model would make our api less error prone but I can see the argument for just leaving it out.

**Review by mcelroyian — CHANGES_REQUESTED** [review]
I recommend removing AnswerMinimum, and refactoring to just use Answer

**Comment by Caleb-Barger** [comment]
Not a problem :dash:

**Review by jiayi-ren — APPROVED** [review]

**Pull request closed without merging**
